Profile creation
PullDating/FlutterApplication pull request #44
Opened 2022-07-08 01:58 UTC by WilliamDormer

Added profile creation screens with partial functionality. Still missing some image handling and backend connectivity.

2022-07-08 05:01 UTC, ethanblake4 requested changes
Other things:
- Update the root gitignore to remove .DS_Store and the .idea stuff (you can copy the gitignore from pull_flutter into the root)
- Run `dart format .` to format everything
- Rename all of the files/folders to use snake case (eg profileCreation => profile_creation)
- Move all of the *field.dart classes into `pull_common`

2022-07-08 05:01 UTC, ethanblake4 commented on pull_flutter/lib/views/profileCreation/heightfield.dart
> +              min: 55,
Make the min and max a configurable variable of `ProfileHeightField`

2022-07-08 13:58 UTC, WilliamDormer commented on pull_common/lib/src/model/entity/profile.dart
> +    double? height,
added comment stating that it uses cm

2022-07-08 14:00 UTC, WilliamDormer commented on pull_common/lib/src/model/provider/create_account.dart
> +class accountCreationNotifier extends StateNotifier<Profile>{
done

2022-07-08 14:13 UTC, WilliamDormer commented on pull_flutter/lib/model/profile_creation_base.dart
> +class ProfileCreationTemplate extends ConsumerStatefulWidget {
done. Commented out the old one in case there is an error when I try to run it.

2022-07-08 14:14 UTC, WilliamDormer commented on pull_flutter/lib/model/routes.dart
> +      path: '/chat/:chatuuid',
done

2022-07-08 14:16 UTC, WilliamDormer commented on pull_flutter/lib/views/chat.dart
> +    _user = types.User(id: "-1"); //the use of the application
not really sure what you want me to change with this one.

2022-07-08 14:16 UTC, WilliamDormer commented on pull_flutter/lib/views/tabs/chats_tab.dart
> +                context.go('/chat/${i}');
done

2022-07-08 14:18 UTC, WilliamDormer commented on pull_flutter/lib/views/tabs/chats_tab.dart
> +                subtitle: Text("You: Most recent text"),
done

2022-07-08 14:18 UTC, WilliamDormer commented on pull_flutter/lib/views/tabs/chats_tab.dart
> +                trailing: Text("Time"),
done

2022-07-08 23:51 UTC, ethanblake4 commented
You missed a bunch of stuff, Cmd+F "hidden conversations". And yeah, not sure about keeping the field classes in pull_common it's fine either way

2022-07-09 00:31 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/bodytypefield.dart
> +    // TODO: implement initState
done

2022-07-09 00:32 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/datinggoalfield.dart
> +    // TODO: implement initState
done

2022-07-09 00:32 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/heightfield.dart
> +    // TODO: implement initState
done

2022-07-09 00:43 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/heightfield.dart
> +      feet = (height!~/30.48);
done

2022-07-09 00:45 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +class Storage {
I'm not sure how to correct this for now. So I'm gonna leave it. You can delete it if you want when you fix up this one.

2022-07-09 00:47 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +                style: GoogleFonts.nunito(
This one was just for the mixed display colour of "Pull", I was trying something out. I don't think we want it as a universal theme.

2022-07-09 00:48 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +      bottomNavigationBar: BottomNavigationBar(
Is this really worth changing? I think it looks good, plus it allows people to click on specific pages, and it has a cool animation.

2022-07-09 00:49 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +      bottomNavigationBar: BottomNavigationBar(
maybe this is something we can change later if user feedback dictates we need to

2022-07-09 00:49 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +      context.go('/createProfile/${tabs!.keys.elementAt(i+1)}');
done

2022-07-09 00:50 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +      var i = tabs!.keys.toList().indexOf(widget.path);
done

2022-07-09 00:50 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +    //_bottomButtonActive = <ValueNotifier<bool>>[
done

2022-07-09 00:50 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +    // TODO: implement initState
done

2022-07-09 00:50 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +        child: tabs![widget.path],
done

2022-07-09 00:51 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +          if (_widget == tabs![widget.path]!) {
done

2022-07-09 00:52 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +class _ProfileCreationParentState extends ConsumerState<ProfileCreationParent> with TickerProviderStateMixin, AutomaticKeepAliveClientMixin{
throws an error when I remove it. Says it's an interface or something that needs to be implemented.

2022-07-09 00:53 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +  bool get wantKeepAlive => true;
no we need this as well apparently, idk why.

2022-07-09 00:57 UTC, WilliamDormer commented on pull_flutter/lib/model/profile_creation_base.dart
> +    required this.nextfunction,
done

2022-07-09 00:57 UTC, WilliamDormer commented on pull_flutter/lib/model/profile_creation_base.dart
> +class Test extends StatelessWidget {
done

2022-07-09 00:58 UTC, WilliamDormer commented on pull_flutter/lib/model/profile_creation_base.dart
> +    final profile = ref.read(accountCreationProvider);
done, I think i removed this when I made it a stateless widget.

2022-07-09 00:58 UTC, WilliamDormer commented on pull_flutter/lib/model/profile_creation_base.dart
> +    final profile = ref.watch(accountCreationProvider);
done when it was changed to stateless widget.

2022-07-09 14:35 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +import 'package:pull_flutter/views/tabs/card_swipe_tab.dart';
done

2022-07-09 15:21 UTC, WilliamDormer commented on pull_flutter/lib/model/profile_creation_base.dart
> +            style: ElevatedButton.styleFrom(
done

2022-07-09 15:22 UTC, WilliamDormer commented on pull_flutter/lib/views/chat.dart
> +    // TODO: implement initState
done

2022-07-09 15:22 UTC, WilliamDormer commented on pull_flutter/lib/views/filters.dart
> +    // TODO: implement initState
done

2022-07-09 15:22 UTC, WilliamDormer commented on pull_flutter/lib/views/filters.dart
> +    distance = 10;
done

2022-07-09 15:23 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/biographyfield.dart
> +    // TODO: implement initState
done

2022-07-09 15:24 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/biographyfield.dart
> +              onChanged: (String value) {
done

2022-07-09 15:34 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/biographyfield.dart
> +                color:(numCharacters >= 300)? Colors.pinkAccent : Colors.black,
done. Using colorScheme.

2022-07-09 15:34 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/birthdatefield.dart
> +    // TODO: implement initState
done

2022-07-09 15:38 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/birthdatefield.dart
> +class _ProfileBirthDateFieldState extends ConsumerState<ProfileBirthDateField> {
is it really worth changing all of these? Maybe in the future, we could do it differently but I don't see a need to go back and change all of them if they're working.

2022-07-09 15:39 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/namefield.dart
> +    Profile myData = ref.watch(accountCreationProvider);
done

2022-07-09 15:39 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +int numPhotos = 0;
done

2022-07-09 15:41 UTC, WilliamDormer commented on pull_flutter/lib/main.dart
> +          bottomNavigationBarTheme: const BottomNavigationBarThemeData(
it is being used by the profile_creation_parent.dart and I figure we may use it in other places.  We can move it to that file if you think it shouldn't be universal though.

2022-07-09 15:43 UTC, WilliamDormer commented on pull_flutter/lib/main.dart
> +          radioTheme: RadioThemeData(
done

2022-07-09 15:43 UTC, WilliamDormer commented on pull_flutter/lib/model/profile_creation_base.dart
> +import 'package:google_fonts/google_fonts.dart';
done

2022-07-09 15:44 UTC, WilliamDormer commented on pull_flutter/lib/model/profile_creation_base.dart
> +          Spacer(flex: 3,),
doesn't like when I use const, but I removed the trailing comma.

2022-07-09 15:45 UTC, WilliamDormer commented on pull_flutter/lib/model/profile_creation_base.dart
> +          Spacer(flex: 3,),
added const to all the spacers.

2022-07-09 15:45 UTC, WilliamDormer commented on pull_flutter/lib/model/routes.dart
> +import 'package:pull_flutter/views/profileCreation/photofield.dart';
done

2022-07-09 15:45 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/biographyfield.dart
> +            Text((numCharacters >= 300)? "Max Characters Reached!" : "${numCharacters}/${maxCharacters}",
done

2022-07-09 15:46 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/birthdatefield.dart
> +import 'package:flutter/cupertino.dart';
done

2022-07-09 15:49 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/birthdatefield.dart
> +import 'package:pull_common/src/model/provider/create_account.dart';
done

2022-07-09 15:49 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/birthdatefield.dart
> +    return Container(
done

2022-07-09 15:50 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/bodytypefield.dart
> +import 'package:flutter/cupertino.dart';
done

2022-07-09 15:51 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/bodytypefield.dart
> +import 'package:pull_common/src/model/provider/create_account.dart';
done

2022-07-09 15:56 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/datinggoalfield.dart
> +import 'package:flutter/cupertino.dart';
done

2022-07-09 15:56 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/datinggoalfield.dart
> +import 'package:pull_common/src/model/provider/create_account.dart';
done

2022-07-09 15:57 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/genderfield.dart
> +import 'package:flutter/cupertino.dart';
done

2022-07-09 15:57 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/genderfield.dart
> +import 'package:pull_common/src/model/provider/create_account.dart';
done

2022-07-09 15:57 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/heightfield.dart
> +import 'package:flutter/cupertino.dart';
done

2022-07-09 15:57 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/heightfield.dart
> +import 'package:pull_common/src/model/provider/create_account.dart';
done

2022-07-09 15:58 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/genderfield.dart
> +    return Container(
done

2022-07-09 15:58 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/genderfield.dart
> +    // TODO: implement initState
done

2022-07-09 15:58 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/heightfield.dart
> +    return Container(
done

2022-07-09 15:59 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/heightfield.dart
> +          Text("${feet}\' ${(inches! < 10)? '0' : ''}${inches}\""),
done

2022-07-09 15:59 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/heightfield.dart
> +                  print("${feet} ${inches}");
done

2022-07-09 16:41 UTC, WilliamDormer reviewed
modified all the things I could

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +                  onPressed: () {
done

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +                  onPressed: () {
reverted, these changes broke the future builder. The file system needs to use the AsyncSnapshot<Directory> to actually get the information. I don't know another way to do it.

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +  Future<Directory>? _appDocDir;
can't make this change, see below

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +                  onPressed: () {
nvm i removed a bunch of stuff and now all it does is get the directory.

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +  Future<Directory>? _appDocDir;
nvm i fixed it.

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +              FutureBuilder<Directory>(
done

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +                  return new Container(
done

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +          radius: Radius.circular(20.0),
done

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +            decoration: BoxDecoration(
done

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +                    decoration: BoxDecoration(
done

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/photofield.dart
> +class Storage {
done

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +import 'package:pull_common/src/model/provider/create_account.dart';
done

2022-07-09 16:41 UTC, WilliamDormer commented on pull_flutter/lib/views/profileCreation/profile_creation_parent.dart
> +      'name' : ProfileCreationTemplate(entryField: ProfileNameField(),title: "Add Your Name",nextfunction: goToNext),
done

2022-08-01 22:56 UTC, WilliamDormer commented
opening more recent pull request.

2022-08-01 22:56 UTC, closed without merging